# Generated by Django 4.2.7 on 2023-11-16 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_customuser_password_alter_customuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="lastname",
        ),
    ]
