# Generated by Django 4.2.7 on 2023-11-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_customuser_password_alter_customuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("files", models.FileField(null=True, upload_to="documents")),
            ],
        ),
    ]
