# Generated by Django 4.2.7 on 2023-11-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_delete_uploadfilemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio", models.FileField(upload_to="audio_files/")),
            ],
        ),
    ]
