# Generated by Django 4.2.7 on 2023-11-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_audiofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="AudioFile",
        ),
    ]
